### ISSUE TITLE
String Index Out of Bounds

### ISSUE THREAD

**Issue by Lal47** [sid24rane/LL1-parser#1]
![image](https://user-images.githubusercontent.com/46594198/114824261-46bea100-9de2-11eb-805c-31fc335da1e7.png)

**Comment by CO18353** [comment]
The error is occurring because of the incorrect regex used for splitting the input into the required format. If you print the "productions" dictionary, you would see that the production rules are incorrectly stored.
So for fixing this error you may either use a correct regex or you may just use the inbuilt split function of python.
Here is what you can do, you can remove the whitespaces and the newline using replace function:
line=line.replace(" ", "").replace("\n", "")
And then split the input at "->" using
l=line.split("->")

**Comment by Hamza-101** [comment]
It works!

**Comment by costi1212** [comment]
This is only a part of the actual fix. If you only use 
line=line.replace(" ", "").replace("\n", "") 
l=line.split("->"
you will not be able to parse grammars containing '|' which means OR correctly, which renders the test grammars and string in the code unusable.
You could actually do something like this:
line=line.replace(" ", "").replace("\n", "")
l = line.split("->")
lhs = l[0]
rhs = set((l[1]).split("|")) 
place this between the line for and flag if in main.

**Comment by SecioreanuStefanita** [comment]
It works!

**Comment by alakdeng** [comment]
how does the pseudo code look like?

**Comment by alakdeng** [comment]
> It works!

how does it look like when added. im having trouble getting rid of the error
